// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;

module.exports = {
  tutorialSidebar: [
    'intro',  // 首頁
    
    // 👇 按照你想要的順序
    {
      type: 'category',
      label: '教育與學習',
      items: [
        {
          type: 'autogenerated',
          dirName: '教育與學習',
        },
      ],
    },
    {
      type: 'category',
      label: '社會',
      items: [
        {
          type: 'autogenerated',
          dirName: '社會',
        },
      ],
    },
    {
      type: 'category',
      label: '社會工作',
      items: [
        {
          type: 'autogenerated',
          dirName: '社會工作',
        },
      ],
    },
    {
      type: 'category',
      label: '心理學',
      items: [
        {
          type: 'autogenerated',
          dirName: '心理學',
        },
      ],
    },
    {
      type: 'category',
      label: '資訊與科技',
      items: [
        {
          type: 'autogenerated',
          dirName: '資訊與科技',
        },
      ],
    },
    {
      type: 'category',
      label: '其他',
      items: [
        {
          type: 'autogenerated',
          dirName: '其他',
        },
      ],
    },
  ],
};
