// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '教育與學習',
      items: [{ type: 'autogenerated', dirName: '教育與學習' }],
    },
    {
      type: 'category',
      label: '社會',
      items: [{ type: 'autogenerated', dirName: '社會' }],
    },
    {
      type: 'category',
      label: '社會工作',
      items: [{ type: 'autogenerated', dirName: '社會工作' }],
    },
    {
      type: 'category',
      label: '社會創新',
      items: [{ type: 'autogenerated', dirName: '社會創新' }],
    },
    {
      type: 'category',
      label: '心理學',
      items: [{ type: 'autogenerated', dirName: '心理學' }],
    },
    {
      type: 'category',
      label: '資訊與科技',
      items: [{ type: 'autogenerated', dirName: '資訊與科技' }],
    },
    {
      type: 'category',
      label: '其他',
      items: [{ type: 'autogenerated', dirName: '其他' }],
    },
  ],
};